name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: prepare

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive Debug Apk
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: debugApk
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Check
      if: success()
      run: ./gradlew lint testDebugUnitTest

    - name: Archive results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test-reports
        path: app/build/reports
